# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = ENV['EMAIL_API_KEY']
  config.secret_key = ENV['EMAIL_SECRET_KEY']
  config.default_from = ENV['EMAIL']

end
